language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: JoelM
  password:
    secure: lerEwYTUSzS5M6LwlV4isPojxzyaJD5ncI37+arjlfIDe4M4aFwGZF9ICIq+ShLWzdjioGnstFl0nN9jWky4OEk4MazeXt/i++kCzMC1+5RxDZF4tvVWm3ioCEj6s3NgoIbXhKX815ROPv5MDG5LrI/8Yqao6A1ZMZRJlQpCIbUWloOwiNQ4F9akoRg5KMFvK66XbQb/WzuMAPoOixolYPO8VtO2EWrCSbOxgYIq4xqSNB8vgIHyAnwPx4ywEeQwrHgEi+6Mi2yatzB6eFZ8ynw7An60lmGhd5edU9zHv5XuZisa7np+QO2BGe+W2/bioyuTj1JLkeEUxJAvr8PuVeIXzeF/OQrTzEXa9WxsR6gYB28Syv08tlkY9SHQEbHZ0D3wYkbRwdURaV/d/7jX6Cx1Uah9uPD8bhHInauA7BgkWqupH9gf6DhxNI75oSDbS+CGkLstQqRe5yYaSlFljBokFMNUA12qZRsTiRfp/BLE2inQ013Vb+HSiJ+5RBfmyRs1LDndIzdc64qQW1j8RDzTISI+v27vw6SSHLxDjQQXq4mkV61j/mr4UuxfppNRY6YsbHSeYFPEGrtfbtXgYRR2gngXL48af4iiZqou8aLyEviityZKOWq8sZ6XiM9ksdgqydFPdvgDhuOBCLNCLzzkv942KTX0E/r10eIxJ/c=
  true:
    tags: true
