language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: JoelM
  password:
    secure: IMbySOIBzywGjV3s2UbatYmXOy1IYzkKKDENN8ry5t+gfzOpwa8eLUpbpY4vdsLMMcv2pYYLDacgreclzfPDWSDPtrNtbfIW8oTo8q3Za3C1QlpvaSmiBZgqaRBZR9RrrqHtBb1OXq4Sai25wQtVRnsUiSqrY6KOidg2VvOJVyBU9ImhFa2k5niuk/rPhtJw0HIYpPykBDHz+DNCy6dH9m2U0zvRsabl4vqHbTIWQxKEWoX9Yvn60diTdFMpuW9tVC2ccAmTBVPXO9dLmqAR2IpfZ6EfUnAMiIiwzXFtj7W4VeLQUY1o1TMLvsEB/xsPvXSFT7SSAiQIPKvjh7qM+G+blOsnxsBCCnWW12NvkVGxwZ/DQlV3e4/rRmaz9mubtwBcFhZ0WOhZg0k64afw8Wv3jK+AvdCeZle3uBtegYi35XJpthSnXFGhfE3V/DUafc+XNDqj01a2Chukg19TwbAWfwNKuJ1KXwMb31tXQqN6ra7Tp3rQnYpDxNpj5Wa9wyQjpt+nfiJ9cmWPiCCy5LH92dCwOTt0KIeEjdPiKV+qmCYxx+cEitr4+ZFV7QJENuwG7Ofo8fnsW5YPNjHYK5N5NJrBTgCt9yR7p/4PwIl0/yxhGyybVgrFhZU22bIImbNh37qNzAxHsbPVw27pO5QkPrzLjWI1j7Cu8r5mzcE=
  on:
    tags: true

