language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  true:
    branch: master
  provider: pypi
  distributions: sdist bdist_wheel
  user: JoelM
  password:
    secure: lPO+3TrfrVVBKi2HF0KTYKC7YIAy4+CEGKFJSWuiuAs8tQyjTZXIIdDY74G2zuO0qtY/Ua+L2UbHxrNihS6eWHMBmKbpTUv9oTvlE2uMrId45Ky8i5FKpW869/y2jCbFfzjYL/Y1VxTStdeU/YtjSPZLjmN9SH2HE0V7CFPTb2u+9lG7xC8PGr7P/uSXZgyI79op20m9/Luq0BqCZsxsPkr1ZNzbG8Vk1mwwy7cazCnuz5pP8rjJKuh0AU310d9taPaa9XJEiHQ4EG7Cr0qPEfwxYsuDirXKnM9uLZQwIWONKTb5QGl4ZEFcuQnn/a8VPt1Q1EuaC02f9H+Adfs7BLGVmHg+mSbc55Dvx9fyPRj6NPtLIG7QNmVifL7vm6UTIDFksuWZCHloA8juRVYInrt8vH1UvF+c9NI4B8I60hPXL5TO0HPNImmhb1r8vceMXyKmvQcp4v1WfeS0Xi8M7/wuekGkRIdhp8eXF5IkQ+W97h8dLLKSNxwP6MfEdC/f2IpcioSlRMi7TOUldwHLVbHli3gXhnzipxE6VM4t/NERCL7KRJDTiHNiznNAiHAMGGKcI4e+j+cyVCiP9qOJ+pzRrKh76Sr3GMRBsYDpvPf9BogL1RZeusVAkXdUAah3jFpTRK1sp17ux+QD5uxcG+TZsJ+nkn5tqMVYF+T2jeM=
