language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: JoelM
  password:
    secure: QxxgcdWRwPCwUP+4/lijsPpGD8zOSlC/yuDxA7TxwF/OxM3KIxQFbUhNdEvBiPhQ3sjtgg9w7QandFf4q50XHYx1++f2DZqfhW04IUNFqybWDMXemTqpEysUa4P83qrfZ+4X+F2DjxMLcwrFtkUH09mpF+zD8u7UxJXiJtOXvD3Iq6+qcohYjr+5vZ3uQHZV3yt5TBbpwPwOQFGLObHACXjjJsRybUluV3idetmwWdSieLCHhKgRD9CiAETRyeC1L0YyPWX+BnAk8ImNxax97mb5AGeH6LwLrAMMQsJjfu48594EZ9oldOxku5JTaq/EH+Ayjq/f1cPyuj7j3csa9euOiGp1i5ZTKrLfD+A8aw0r4Nb+tJgmHO2gO35boqN+UoIZtZ8D01B2m4aLyNjVlTtfiD5obCAuJRHnTC03KE8njwbjDN7XrB2wbgFPoO/wYagpoAJr67DSIVyKP4d1kZsZhp7aKdxwo6cNAkQaKAmbuLlz6UfU4/DTzwhi5KI5qZMw7mPpnpC74LP2FU+RGsDx2RySATPq3eLggwx3xdAmnS4E+uSqsgbV+3vNxBmAskuxByYr/2iBRz2nozkQpfiv2k2u59osRbGZXMolgxYR9ltapc7XcAdBIMBc3RqZTZxhWUdQhHar2Mlsrjif42pUC8qtRDnpnDob4w1sqsc=
  true:
    tags: true
    repo: JoelMon/namedex
    python: 3.6
