language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: JoelM
  password:
    secure: RIksIPjm4z6Gi2Zn/zh7Ted0jUe4//6ZxLM/5Es/EVVMZwMaGn0SVncElyRO6hzq+a12afbU442aqzfktJHYrAYxIgm3Yuzke+h4Tjv/qaJhXpL/ZXNtaYC6MsG8/tX5B05EuT8j2g14i29jag5BDKcDUR5vi8gv2X+1Gj/sCE7jaxQd7rKlIMRpNC2XYrXzgSkLYGk+hMGVJDFhDtfaFHtGHYplRq/1P5MzoEDdot5P5Id+S5AI44PWgxLSJfWWy5lMC6ex67RSxcQMyGmGmneT0epQAsuYop8l0z9D+RzwXIsANZwmmJ5JsutE0AQmV2qg4WiyfgMYL6c/c2WcAZAABRv9lJjA+m8YEz10LgIuh8Bz/UuOIkred/YcTnmnJ9Gs+MbyPBO9K2Y0lXKtJPLGbLYVqY5a0g1ZW4HVXUAxaVuYB1EX48gYFtpsu3g6v6SilxJEYCG8cL5+1SK0GH2+z+Zx5YmOxpi+87gF6nQ3ekqlOi4nVgdwk8CU4RevgHlbB92nyNp3Jn+hYs3hs6uDnCsZWvqk4YuzSNpnNQ5Y0jGWPVbvEE3JTY9Ofpm2BEs62U0n+go/hewB1nB7KKyorNJEr7MtGh0aoBDpYcKX2vg2luBAO0TByPp0MYoPPlC9WCowjKQTZo6SsQW5mcqlGmV2hpm2/iSsVdNm+G4=
  true:
    tags: true
