language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  true:
    branch: master
  provider: pypi
  distributions: sdist bdist_wheel
  user: JoelM
  password:
    secure: oCC1AErU/DEUALl6bX0pTlgGH4zWKy2SjwKJjGBCWV74ds+5d4bhBc85Ughpynzi5u9uYYf6LbDXoAzTzN4IR3WFf0jrFwz0TdzQAspvDB+uLJvU7n7bMuTD55DQwfQe34KTggUbPYtEtORip22shmFTYwL1lGprNmP+pOlnWe/Zl9eVSmxfDbaiOvXJAqE675wqN5vGD4XDiDXB1t+35gJnfACZKO5uM6GcpaGE1AgD2V4Ko0KaaiUcR+lL1io4b4a19enaXfGdjtZGctZJ3hiCVT9aeyUlq9T+1v1XguxK65WHF5py4RNc2wDFz0QBjsexp1BNT1m1pWkEgOcVp5a7dE7Hs1ke80/1Wz/AA7afhAIh/kyyy0299P6qua43t3GfkuY1ay7LPtOV4YWl0wyNPdeixZmbJ/H5wxNv0XSIU3TgkGFMFw99eHHLVyACCQxXRdOxUYLlYLmix1dk9yDBrHZdRksJWtXSwc4gyWPfgO8uzjJuZrRxf9zObCO5jHC2DDT7kDWCXdr6qg7iHP5/cCdhmQIgHXF7oS99jsnu2H+KG4TKVIgpUfHXECAVjJBFlPZSxZ/7/M2EGpHV16a7flHTVwpYSp9VXrWr8OEqBfUq2nWmXdjAiOzr49UTDsisQLNPKHTAwd+u/MLg6ONV2N3OTRX5kfcrzEI4naM=
